home/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'home'

urlpatterns = [
    path('', home_view, name='homepage'),
    # path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('courses', courses_view, name='courses'),
    path('login', login_view, name='login'),
    path('dashboard', dashboard_view, name='dashboard'),
    path('lesson/<int:pk>', lesson_view, name='lesson'),
    path('lesson-detail/<int:pk>', lesson_detail_view, name='lesson-detail'),
    path('register', register_view, name='register'),
    path('logout', userlogout, name='logout'),
    path('upload_audio/<int:pk>', upload_audio, name='upload_audio'),
    path('payment-verify', verify_payment, name='verify_payment'),
    path('unsubscribed', reset_subscription_counter_job, name='reset_subscription'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

language/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.contrib.auth.models import User
from django.db import models


STATUS_CHOICES = (
    ("running", "Running"), ("completed", "Completed")
)

TRANSACTION_STATUS_CHOICES = (
    ("pending", "Pending"), ("success", "Success"), ("failed", "Failed")
)

VOCABULARY_STATUS_CHOICES = (
    ("completed", "Completed"), ("not_completed", "Not Completed")
)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateTimeField(blank=True, null=True)
    level = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=30, blank=True, null=True)
    stripe_customer_id = models.CharField(max_length=400, blank=True, null=True)
    subscribed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Lesson(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="course-images", blank=True, null=True)
    price = models.FloatField()

    def __str__(self):
        return self.name


class UserLesson(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, blank=True, null=True)
    progress = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="running")

    def __str__(self):
        return f"{self.user.username}: {self.lesson.name}"


class Vocabulary(models.Model):
    title = models.CharField(max_length=50)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    text = models.TextField()
    image = models.ImageField(upload_to="vocabulary-images", blank=True, null=True)
    audio_file = models.FileField(blank=True, null=True, upload_to="audio-files")
    video_file = models.FileField(blank=True, null=True, upload_to="video-files")

    def __str__(self):
        return f"{self.title}: {self.lesson.name}"


class UserVocabulary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vocabulary = models.ForeignKey(Vocabulary, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="running")

    def __str__(self):
        return self.vocabulary.title


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # plan = models.ForeignKey(Lesson, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.DecimalField(default=0, decimal_places=2, max_digits=20)
    status = models.CharField(max_length=50, choices=TRANSACTION_STATUS_CHOICES, default="pending")
    detail = models.CharField(max_length=200, blank=True, null=True)
    transaction_id = models.CharField(max_length=200, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}: {self.status}"

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from home.models import *


class AudioForm(forms.Form):
    audio = forms.FileField()


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)


class RegistrationForm(forms.Form):
    email = forms.EmailField(help_text='Required. Input a valid email address.', required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    password = forms.CharField(required=True)
    phone = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        email = self.cleaned_data.get('email').lower()
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        password2 = self.cleaned_data.get('password')
        # dob = self.cleaned_data.get('dob')

        user, user_created = User.objects.get_or_create(username=email)
        user.email = email
        user.first_name = first_name
        user.last_name = last_name
        user.password = make_password(password2)
        user.save()

        profile, profile_created = UserProfile.objects.get_or_create(user=user)
        # profile.dob = dob
        profile.save()

        return user


# class ContactForm(forms.ModelForm):
#     class Meta:
#         model = Contact
#         exclude = []


# class SetNewPasswordForm(PasswordChangeForm):
#     class Meta:
#         model = User
#         exclude = []

home/views.py
import datetime
import os
import uuid
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect

from home.forms import LoginForm, RegistrationForm, AudioForm
from home.models import *
from home.stripe_api import StripeAPI
from home.utils import complete_payment, transcribe_audio, payment_checkout

baseUrl = settings.BASE_URL


def home_view(request):
    context = {
        'plans': Lesson.objects.all().order_by('price')[:3],
    }
    return render(request, 'home/index.html', context)


def about_view(request):
    context = {}
    return render(request, 'home/about.html', context)


def contact_view(request):
    context = {}
    return render(request, 'home/contact.html', context)


def courses_view(request):
    courses = Lesson.objects.all().order_by("price")
    context = {
        'courses': courses,
    }
    return render(request, 'home/courses.html', context)


def login_view(request):
    # if request.user.is_authenticated:
    #     return redirect('/dashboard')

    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=email, password=password)
            if user is not None:
                # Check if user is subscribed
                user_profile = UserProfile.objects.get(user=user)
                if not user_profile.subscribed:
                    # Redirect to stripe:
                    success, url = payment_checkout(user_profile)
                    if success:
                        return HttpResponseRedirect(url)
                    else:
                        messages.error(request, 'Your subscription has expired')
                        return redirect(reverse('home:login'))
                # Get all Lessons
                lessons = Lesson.objects.all()
                for lesson in lessons:
                    UserLesson.objects.get_or_create(user=user, lesson=lesson)
                    volca = Vocabulary.objects.filter(lesson=lesson)
                    for vol in volca:
                        UserVocabulary.objects.get_or_create(user=user, vocabulary=vol)
                login(request, user)
                return redirect('/dashboard')
            else:
                messages.error(request, 'Login details are not correct')
                return redirect(reverse('home:login'))
    context = {
        'form': form,
    }
    return render(request, 'home/login.html', context)


def register_view(request):
    form = RegistrationForm()

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            get_email = User.objects.filter(email=form.cleaned_data.get('email'))
            if get_email:
                messages.error(request, 'Email address already registered')
                return redirect(reverse('home:register'))

            user_form = form.save()
            # CREATE USER PROFILE
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            phone = form.cleaned_data.get('phone')
            user = authenticate(request, username=email, password=password)
            user_profile, created = UserProfile.objects.get_or_create(user=user)
            user_profile.phone_number = phone
            user_profile.save()
            amount = float(1.0)
            callback_url = f"{baseUrl}/payment-verify"
            stripe_customer_id = ""
            if not user_profile.stripe_customer_id:
                customer = StripeAPI.create_customer(
                    name=user.get_full_name(),
                    email=user.email,
                    phone=phone
                )
                user_profile.stripe_customer_id = customer.get('id')
                user_profile.save()
                stripe_customer_id = customer.get('id')
            description = f"Course Payment for {datetime.datetime.now().strftime('%B %Y')}"

            while True:
                # payment_reference = payment_link = None
                success, response = StripeAPI.create_payment_session(
                    name=user.get_full_name(),
                    amount=amount,
                    return_url=callback_url,
                    customer_id=stripe_customer_id,
                )
                if not success:
                    # raise InvalidRequestException({'detail': response})
                    # DELETE USER
                    User.objects.get(email=email).delete()
                    messages.success(request, 'Error generating payment link, please try later')
                    return redirect('/')
                if not response.get('url'):
                    # DELETE USER
                    User.objects.get(email=email).delete()
                    messages.success(request, 'Error generating payment link, please try later')
                    return redirect('/')

                payment_reference = response.get('payment_intent')
                if not payment_reference:
                    payment_reference = response.get('id')
                payment_link = response.get('url')
                break

            # Create Transaction
            Transaction.objects.create(user=user, amount=amount, detail=description, transaction_id=payment_reference)

            return HttpResponseRedirect(payment_link)

            # messages.success(request, 'Account registered successfully')
            # return redirect('/login')

    context = {
        'form': form,
    }
    return render(request, 'home/register.html', context)


def userlogout(request):
    logout(request)
    return redirect('/')


@login_required(login_url='/login')
def dashboard_view(request):
    profile = UserProfile.objects.filter(user=request.user).last()

    context = {
        'profile': profile,
        'completed': UserLesson.objects.filter(user=request.user, status="completed"),
        'running': UserLesson.objects.filter(user=request.user, status="running"),
        'transactions': Transaction.objects.filter(user=request.user).order_by("-id")[:20],
        'total_transaction': Transaction.objects.filter(user=request.user),
    }
    return render(request, 'home/dashboard.html', context)


@login_required(login_url='/login')
def lesson_view(request, pk):
    profile = UserProfile.objects.get(user=request.user)
    lesson = UserLesson.objects.get(id=pk)
    user_vocabularies = [{
        "id": item.id,
        "title": item.vocabulary.title,
        "status": item.status,
        "text": item.vocabulary.text,
        "image": item.vocabulary.image,
    } for item in UserVocabulary.objects.filter(vocabulary__lesson=lesson.lesson)]

    context = {
        'profile': profile,
        'lesson': lesson,
        'user_vocabularies': user_vocabularies
    }
    return render(request, 'home/lesson.html', context)


def lesson_detail_view(request, pk):
    profile = UserProfile.objects.get(user=request.user)

    context = {
        'profile': profile,
        'volca': UserVocabulary.objects.get(id=pk, user=request.user),
    }
    return render(request, 'home/lesson-detail.html', context)


def upload_audio(request, pk):
    # GET Volcabulary
    volca = UserVocabulary.objects.get(id=pk)
    text = volca.vocabulary.text
    if request.method == 'POST':
        form = AudioForm(request.POST, request.FILES)
        if form.is_valid():
            audio_file = form.cleaned_data['audio']
            random_filename = f"{uuid.uuid4()}.wav"
            audio_path = os.path.join(settings.MEDIA_ROOT, 'audio', random_filename)

            # Ensure the media directory exists
            os.makedirs(os.path.dirname(audio_path), exist_ok=True)

            with open(audio_path, 'wb') as f:
                for chunk in audio_file.chunks():
                    f.write(chunk)

                response = transcribe_audio(file_path=audio_path, file_name=random_filename)
                if str(response).lower() != str(text).lower():
                    messages.error(request, f'Words mismatch!!!')
                    messages.error(request, f'Course Text: {text}')
                    messages.error(request, f'Your Response: {response}')
                    return redirect(reverse('home:upload_audio', args=[pk]))
                # Update UserVocabulary to complete
                volca.status = "completed"
                volca.save()
            return redirect(reverse('home:lesson-detail', args=[pk]))
    else:
        form = AudioForm()
    return render(request, 'home/audio.html', {'form': form})


def verify_payment(request):
    reference = request.GET.get("reference")
    success, response = complete_payment(reference)
    if success is False:
        return redirect(reverse('home:homepage'))
    #     return Response({"detail": response}, status=status.HTTP_400_BAD_REQUEST)
    return redirect(reverse('home:dashboard',))


def reset_subscription_counter_job(request):
    site_password = settings.RESET_SUBSCRIPTION_PASSWORD
    password = request.GET.get("password")
    if password != site_password:
        return JsonResponse({"detail": "Incorrect Password"})
    UserProfile.objects.all().update(subscribed=False)
    return JsonResponse({"detail": "All users unsubscribed!!!"})

home/templates/home/base.html
{% load static %}

{% block head %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>New York English | Learn English</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'home/' %}assets/img/favicon.ico">

    <!-- CSS here -->
    <link
    href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css"
    rel="stylesheet"
/>
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/slicknav.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/flaticon.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/progressbar_barfiller.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/gijgo.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/animate.min.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/animated-headline.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/magnific-popup.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/themify-icons.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/slick.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/nice-select.css">
    <link rel="stylesheet" href="{% static 'home/' %}assets/css/style.css">

</head>

<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'home/' %}assets/img/logo/loader-new.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area header-transparent">
            <div class="main-header ">
                <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo">
                                    <a href="{% url 'home:homepage' %}"><img src="{% static 'home/' %}assets/img/logo/logo-new.png" alt="" style="height: 10rem; width: 20rem; padding-top: 1rem; " </a>
                                    <br>
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10">
                                <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                    <!-- Main-menu -->
                                    <div class="main-menu d-none d-lg-block">
                                        <nav>
                                            <ul id="navigation">
                                                <li class="active" ><a style="color: white" href="{% url 'home:homepage' %}">Home</a></li>
                                                <li><a style="color: white" href="{% url 'home:courses' %}">Subsription</a></li>
{#                                                <li><a href="{% url 'home:about' %}">About</a></li>#}
{#                                                <li><a href="#">Blog</a>#}
{#                                                    <ul class="submenu">#}
{#                                                        <li><a href="blog.html">Blog</a></li>#}
{#                                                        <li><a href="blog_details.html">Blog Details</a></li>#}
{#                                                        <li><a href="elements.html">Element</a></li>#}
{#                                                    </ul>#}
{#                                                </li>#}
                                                <li><a style="color: white" href="{% url 'home:contact' %}">Contact</a></li>
                                            {% if user.is_authenticated %}
                                                <li><a style="color: white" href="{% url 'home:dashboard' %}">Dashboard</a></li>
                                                <li class="button-header"><a href="{% url 'home:logout' %}" class="btn btn3">Logout</a></li>
                                                <!-- Button -->
                                                {% else %}
                                                    <li class="button-header margin-left "><a style="color: white" href="{% url 'home:register' %}" class="btn">Join</a></li>
                                                    <li class="button-header"><a style="color: white" href="{% url 'home:login' %}" class="btn btn3">Log in</a></li>
                                                {% endif %}
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>
{% endblock %}

{% block body %}

{% endblock %}

{% block footer %}
    <footer>
     <div class="footer-wrappper footer-bg">
        <!-- Footer Start-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-xl-4 col-lg-5 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo mb-25">
                                    <a href="{% url 'home:homepage' %}><img src="{% static 'home/' %}assets/img/logo/logo2_footer.png" alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                </div>
                                <!-- social -->
                                <div class="footer-social">
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Our solutions</h4>
                                <ul>
                                    <li><a href="#">Plans</a></li>
                                    <li><a href="#">Community</a></li>
                                    <li><a href="#">FAQs</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-4 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Support</h4>
                                <ul>
                                    <li><a href="#">Contact Us</a></li>
{#                                    <li><a href="#">Telecommunication</a></li>#}
{#                                    <li><a href="#">Restaurant</a></li>#}
{#                                    <li><a href="#">Programing</a></li>#}
{#                                    <li><a href="#">Architecture</a></li>#}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Quick Links</h4>
                                <ul>
{#                                    <li><a href="#">About Us</a></li>#}
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Resources</a></li>
                                    <li><a href="#">Copyright</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer-bottom area -->
        <div class="footer-bottom-area">
            <div class="container">
                <div class="footer-border">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-12 ">
                            <div class="footer-copy-right text-center">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
                                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!-- Footer End-->
      </div>
  </footer>
  <!-- Scroll Up -->
  <div id="back-top" >
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>

<!-- JS here -->
<script src="{% static 'home/' %}assets/js/vendor/modernizr-3.5.0.min.js"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'home/' %}assets/js/vendor/jquery-1.12.4.min.js"></script>
<script src="{% static 'home/' %}assets/js/popper.min.js"></script>
<script src="{% static 'home/' %}assets/js/bootstrap.min.js"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'home/' %}assets/js/jquery.slicknav.min.js"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'home/' %}assets/js/owl.carousel.min.js"></script>
<script src="{% static 'home/' %}assets/js/slick.min.js"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static 'home/' %}assets/js/wow.min.js"></script>
<script src="{% static 'home/' %}assets/js/animated.headline.js"></script>
<script src="{% static 'home/' %}assets/js/jquery.magnific-popup.js"></script>

<!-- Date Picker -->
<script src="{% static 'home/' %}assets/js/gijgo.min.js"></script>
<!-- Nice-select, sticky -->
<script src="{% static 'home/' %}assets/js/jquery.nice-select.min.js"></script>
<script src="{% static 'home/' %}assets/js/jquery.sticky.js"></script>
<!-- Progress -->
<script src="{% static 'home/' %}assets/js/jquery.barfiller.js"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static 'home/' %}assets/js/jquery.counterup.min.js"></script>
<script src="{% static 'home/' %}assets/js/waypoints.min.js"></script>
<script src="{% static 'home/' %}assets/js/jquery.countdown.min.js"></script>
<script src="{% static 'home/' %}assets/js/hover-direction-snake.min.js"></script>

<!-- contact js -->
<script src="{% static 'home/' %}assets/js/contact.js"></script>
<script src="{% static 'home/' %}assets/js/jquery.form.js"></script>
<script src="{% static 'home/' %}assets/js/jquery.validate.min.js"></script>
<script src="{% static 'home/' %}assets/js/mail-script.js"></script>
<script src="{% static 'home/' %}assets/js/jquery.ajaxchimp.min.js"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'home/' %}assets/js/plugins.js"></script>
<script src="{% static 'home/' %}assets/js/main.js"></script>
<script defer src="{% static 'home/' %}assets/js/recorder.js"></script>

</body>
</html>
{% endblock %}

home/templates/home/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>